# Clean Julia REPL session saved on 2026-06-16T21:22:33.024
# Generated by jEMach

using AtractorsQGP

mis = load_dataset("datasets/ncbj_xin_2020_5000.h5")

println(plot_pca_evr_over_time)

using AtractorsQGP

using GLMakie

w_max = 2.5

attr = attractor_data(MISModel(), tau_max = w_max, krok = 0.005)

mis = load_dataset("datasets/ncbj_xin_2020_5000.h5")

using AtractorsQGP

using GLMakie

mis = load_dataset("datasets/ncbj_xin_2020_5000.h5")

trajs = AtractorsQGP._split_trajectories(mis)

T0_target = 5.96

tol = 0.05

wybrane = [tr for tr in trajs if abs(mis[tr[1], 2] - T0_target) < tol]

mis_filtered = reduce(vcat, [mis[tr, :] for tr in wybrane])

model = MISModel()

attr = attractor_data(model, tau_max = 5.0, krok = 0.01)

fig = plot_attractor(mis_filtered, attractor = attr, n_trajectories = length(wybrane))

T0_target = 2

fig = plot_attractor(mis_filtered, attractor = attr, n_trajectories = length(wybrane))

using AtractorsQGP

mis = load_dataset("datasets/ncbj_xin_2020_5000.h5")

model = MISModel()

attr = attractor_data(model, tau_max = 5.0, krok = 0.01)

fig = plot_attractor(mis, 5.96, attractor = attr, tol = 0.02, n_trajectories = 50)

fig = plot_attractor(mis, 2, attractor = attr, tol = 0.02, n_trajectories = 50)

fig = plot_attractor(mis, 2.5, attractor = attr, tol = 0.02, n_trajectories = 50)

fig = plot_attractor(mis, 3, attractor = attr, tol = 0.02, n_trajectories = 50)

save("plots/attractor/A_W_T_3.pdf", fig)

save("plots/attractor/A_W_T_3.pdf", fig)

fig = plot_attractor(mis, 3, attractor = attr, tol = 0.02, n_trajectories = 100)

save("plots/attractor/A_W_T_3.pdf", fig)

fig_2= plot_attractor(mis, 5, attractor = attr, tol = 0.02, n_trajectories = 100)

save("plots/attractor/A_W_T_5.pdf", fig_2)

long_mis = load_dataset("datasets/MIS_10fm5000.h5")

att_ps = plot_phase_space_grid(long_mis, [0.8, 1:2:10...], :T, :A, attractor = attr)

att_ps = plot_phase_space_grid(long_mis, [0.8, 1:2:10...], :T, :A, attractor = attr);

attr = attractor_data(model, tau_max = 10.0, krok = 0.01)

att_ps = plot_phase_space_grid(long_mis, [0.8, 1:2:10...], :T, :A, attractor = attr);

att_ps = plot_phase_space_grid(long_mis, [0.8, 1:2:10...], :T, :A, attractor = attr)

save("plots/attractor/late_time_ATTR.pdf",  att_ps)

TTtau = plot_phase_space_grid(mis, [0.2, 0.25:0.1:0.65...], :tauT_2020, :tau2Tdot_2020, attractor=attr)

save("plots/phase_space/phase_space_dT_T1_2020_1.pdf",  TTtau)

TTtau2 = plot_phase_space_grid(long_mis, [0.8, 1:2:10...], :tauT_2020, :tau2Tdot_2020, attractor=attr)

TTtau2 = plot_phase_space_grid(long_mis, [0.2,0.3,0.7,0.8, 1:2:10...], :tauT_2020, :tau2Tdot_2020, attractor=attr)

save("plots/phase_space/phase_space_dT_T1_2020_2.pdf",  TTtau2)

fig

fig_2

dane_atraktora = attractor_data(MISModel(); tau_max = 10, krok = 0.01)

taus = [0.2, 0.25:0.1:0.65...]

dane_atraktora = attractor_data(MISModel(); tau_max = 10, krok = 0.01)

ps = plot_phase_space_grid(mis, taus, :T, :A, attractor = dane_atraktora)

fig = plot_pca_evr_over_time(
    mis;
    n_components = 2,
    feature_cols = [:tauT_2020, :tau2Tdot_2020]
)

plot_pca_evr_over_time(mis, plot_title=L"\text{EVR w funkcji czasu w przestrzeni fazowej } T/T\_0
, A", feature_cols=[:tauT_2020, :tau2Tdot_2020])

plot_pca_evr_over_time(mis, plot_title=L"\text{EVR w funkcji czasu w przestrzeni fazowej } \tau T, \tau^2 \dot{T} ", feature_cols=[:tauT_2020, :tau2Tdot_2020])

plot_pca_evr_over_time(mis, plot_title=L"\text{EVR w funkcji czasu w przestrzeni fazowej } \tau_0 T, \tau_{0}^{2} \dot{T} ", feature_cols=[:tauT_2020, :tau2Tdot_2020])

ttauT2= plot_pca_evr_over_time(mis, plot_title=L"\text{EVR w funkcji czasu w przestrzeni fazowej } \tau_0 T, \tau_{0}^{2} \dot{T} ", feature_cols=[:tauT_2020, :tau2Tdot_2020])

save("plots/EVR/T_dotTtau2.pdf", ttauT2)

ttauT2= plot_pca_evr_over_time(mis, plot_title=L"\text{EVR w funkcji czasu w przestrzeni fazowej } T, \mathcal{A}", feature_cols=[:T, :A])

save("plots/EVR/EVR_PCA_TA.pdf", ttauT2)

ps = plot_phase_space_grid(mis, taus, :T, :A, attractor = dane_atraktora)

save("plots/phase_space/ps_AT_locked_limits.pdf", ps)

fig_2

typeof(fig_2)

