# Clean Julia REPL session saved on 2026-06-16T18:01:59.510
# Generated by jEMach

using AtractorsQGP

mis = load_dataset("datasets/ncbj_xin_2020_5000.h5")

println(plot_pca_evr_over_time)

using AtractorsQGP

using GLMakie

w_max = 2.5

mis = load_dataset("datasets/ncbj_xin_2020_5000.h5")

using AtractorsQGP

using GLMakie

mis = load_dataset("datasets/ncbj_xin_2020_5000.h5")

trajs = AtractorsQGP._split_trajectories(mis)

T0_target = 5.96

tol = 0.05

model = MISModel()

attr = attractor_data(model, tau_max = 5.0, krok = 0.01)

T0_target = 2

using AtractorsQGP

mis = load_dataset("datasets/ncbj_xin_2020_5000.h5")

model = MISModel()

attr = attractor_data(model, tau_max = 5.0, krok = 0.01)

fig = plot_attractor(mis, 5.96, attractor = attr, tol = 0.02, n_trajectories = 50)

fig = plot_attractor(mis, 2, attractor = attr, tol = 0.02, n_trajectories = 50)

fig = plot_attractor(mis, 2.5, attractor = attr, tol = 0.02, n_trajectories = 50)

fig = plot_attractor(mis, 3, attractor = attr, tol = 0.02, n_trajectories = 50)

save("plots/attractor/A_W_T_3.pdf", fig)

save("plots/attractor/A_W_T_3.pdf", fig)

fig = plot_attractor(mis, 3, attractor = attr, tol = 0.02, n_trajectories = 100)

save("plots/attractor/A_W_T_3.pdf", fig)

fig_2= plot_attractor(mis, 5, attractor = attr, tol = 0.02, n_trajectories = 100)

save("plots/attractor/A_W_T_5.pdf", fig_2)

long_mis = load_dataset("datasets/MIS_10fm5000.h5")

att_ps = plot_phase_space_grid(long_mis, [0.8, 1:2:10...], :T, :A, attractor = attr)

att_ps = plot_phase_space_grid(long_mis, [0.8, 1:2:10...], :T, :A, attractor = attr);

attr = attractor_data(model, tau_max = 10.0, krok = 0.01)

att_ps = plot_phase_space_grid(long_mis, [0.8, 1:2:10...], :T, :A, attractor = attr);

